###
POST http://localhost:8080/api/process/
Content-Type: application/json

{
  "id": 116,
  "title": "coffee",
  "discontinued": false,
  "stage": [
    {
      "id": 122,
      "question": "WHY",
      "stageOrder": 222,
      "type": "boolean"
    }
  ]
}

###
POST http://localhost:8080/api/process/
Content-Type: application/json

{
  "title": "coffee",
  "discontinued": false,
  "stage": []
}

###
POST http://localhost:8080/api/stage/
Content-Type: application/json

    {
      "processId": 112,
      "question": "Cake?",
      "stageOrder": 2,
      "type": "boolean",
      "stageOptions": []
    }

###
POST http://localhost:8080/api/stage/
Content-Type: application/json

{
  "processId": 111,
  "question": "WHY",
  "stageOrder": 2,
  "type": "boolean"
}

