###
POST http://localhost:8080/api/process/
Content-Type: application/json

{
  "title": "coffee",
  "discontinued": false,
  "stage": [
    {
      "question": "WHY",
      "stageOrder": 222,
      "type": "boolean"
    }
  ]
}

###
POST http://localhost:8080/api/process/
Content-Type: application/json

{
  "title": "coffee",
  "discontinued": false,
  "stage": []
}

###
POST http://localhost:8080/api/stage/
Content-Type: application/json

    {
      "processId": 99,
      "question": "Cake?",
      "stageOrder": 222,
      "type": "boolean"
    }

###
POST http://localhost:8080/api/stage/
Content-Type: application/json

{
  "processId": 5,
  "question": "WHY",
  "stageOrder": 222,
  "type": "boolean"
}

